# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv

# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g., lanes or resequencing of the same biological
# sample).
units: units.tsv

genome: "data/genome/potato_dm_v404_all_pm_un.fasta"

# sequencing adapter
adapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTGTTCCTGAGTGTAGATCTCGGTGGTCGCCGTATCATT

params:
    cutadapt-pe: "-q 10 -m 40 -j 8"
    cutadapt-se: "-q 10 -m 40 -j 8"

controlfile: "LOP868-SRR6123032_coverage.bed"

diploid_bams:
    - data/dedup/2x_LOP868_004-KFRAG_00003H-dedup-sorted.aln.bam
    - data/dedup/2x_LOP868_064-KFRAG_00028H-dedup-sorted.aln.bam
    - data/dedup/2x_LOP868_305-KFRAG_00092H-dedup-sorted.aln.bam
    - data/dedup/2x_IVP101-SRR6123183-dedup-sorted.aln.bam
    - data/dedup/2x_PL4-SRR6123031-dedup-sorted.aln.bam

tetraploid_bams:
    - data/dedup/4x_LOP868-SRR6123032-dedup-sorted.aln.bam

diploid_gvcfs:
    - data/calls/gatk/2x_LOP868_004-KFRAG_00003H.g.vcf
    - data/calls/gatk/2x_LOP868_064-KFRAG_00028H.g.vcf
    - data/calls/gatk/2x_LOP868_305-KFRAG_00092H.g.vcf
    - data/calls/gatk/2x_IVP101-SRR6123183.g.vcf
    - data/calls/gatk/2x_PL4-SRR6123031.g.vcf

tetraploid_gvcfs:
    - data/calls/gatk/4x_LOP868-SRR6123032.g.vcf

targets:
    - data/dedup/2x_LOP868_004-KFRAG_00003H-dedup-sorted.aln.bam.bai
    - data/dedup/2x_LOP868_064-KFRAG_00028H-dedup-sorted.aln.bam.bai
    - data/dedup/2x_LOP868_305-KFRAG_00092H-dedup-sorted.aln.bam.bai
    - data/dedup/4x_LOP868-SRR6123032-dedup-sorted.aln.bam.bai
    - data/dedup/2x_IVP101-SRR6123183-dedup-sorted.aln.bam.bai
    - data/dedup/2x_PL4-SRR6123031-dedup-sorted.aln.bam.bai
