# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g., lanes or resequencing of the same biological
# sample).
units: units.tsv

genome: "data/genome/potato_dm_v404_all_pm_un.fasta"

# sequencing adapter
adapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTGTTCCTGAGTGTAGATCTCGGTGGTCGCCGTATCATT

params:
    cutadapt-pe: "-q 10 -m 40 -j 8"
    cutadapt-se: "-q 10 -m 40 -j 8"
    align:
        bwa_threads: 12
        sort_threads: 4
        sort_mem: 4G
    gatk_genotype_gvcfs:
       threads: 12

vcfs:
    diploid:
        - data/calls/gatk/2x_LOP868_004-KFRAG_00003H.g.vcf
        - data/calls/gatk/2x_LOP868_064-KFRAG_00028H.g.vcf
        - data/calls/gatk/2x_LOP868_305-KFRAG_00092H.g.vcf
        - data/calls/gatk/2x_IVP101-SRR6123183.g.vcf
        - data/calls/gatk/2x_PL4-SRR6123031.g.vcf
    tetraploid:
        - data/calls/gatk/4x_LOP868-SRR6123032.g.vcf
    combined: 
        - data/calls/gatk/all-calls.vcf

controlfile: "LOP868-SRR6123032_coverage.bed"
